### ISSUE TITLE
Improve thread safety

### ISSUE THREAD

**Issue by bboe** [bboe/update_checker#13]
The following exception appears to be due to thread-safety. Fix it and look for other places where similar race conditions could occur:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "run.py", line 53, in run
    self.ufk.login()
  File "/opt/redditbots/bots/bot.py", line 29, in login
    user_agent = "Karma monster for " + self.subreddit)
  File "/usr/local/lib/python2.7/dist-packages/praw/reddit.py", line 121, in __init__
    self._check_for_update()
  File "/usr/local/lib/python2.7/dist-packages/praw/reddit.py", line 242, in _check_for_update
    update_check(__package__, __version__)
  File "/usr/local/lib/python2.7/dist-packages/update_checker.py", line 177, in update_check
    result = checker.check(package_name, package_version, **extra_data)
  File "/usr/local/lib/python2.7/dist-packages/update_checker.py", line 68, in wrapped
    retval = function(obj, package_name, package_version, **extra_data)
  File "/usr/local/lib/python2.7/dist-packages/update_checker.py", line 144, in check
    release_date=data['data']['upload_time'])
  File "/usr/local/lib/python2.7/dist-packages/update_checker.py", line 89, in __init__
    '%Y-%m-%dT%H:%M:%S')
AttributeError: _strptime

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "run.py", line 53, in run
    self.ufk.login()
  File "/opt/redditbots/bots/bot.py", line 29, in login
    user_agent = "Karma monster for " + self.subreddit)
  File "/usr/local/lib/python2.7/dist-packages/praw/reddit.py", line 121, in __init__
    self._check_for_update()
  File "/usr/local/lib/python2.7/dist-packages/praw/reddit.py", line 242, in _check_for_update
    update_check(__package__, __version__)
  File "/usr/local/lib/python2.7/dist-packages/update_checker.py", line 177, in update_check
    result = checker.check(package_name, package_version, **extra_data)
  File "/usr/local/lib/python2.7/dist-packages/update_checker.py", line 68, in wrapped
    retval = function(obj, package_name, package_version, **extra_data)
  File "/usr/local/lib/python2.7/dist-packages/update_checker.py", line 144, in check
    release_date=data['data']['upload_time'])
  File "/usr/local/lib/python2.7/dist-packages/update_checker.py", line 89, in __init__
    '%Y-%m-%dT%H:%M:%S')
AttributeError: _strptime

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "run.py", line 53, in run
    self.ufk.login()
  File "/opt/redditbots/bots/bot.py", line 29, in login
    user_agent = "Karma monster for " + self.subreddit)
  File "/usr/local/lib/python2.7/dist-packages/praw/reddit.py", line 121, in __init__
    self._check_for_update()
  File "/usr/local/lib/python2.7/dist-packages/praw/reddit.py", line 242, in _check_for_update
    update_check(__package__, __version__)
  File "/usr/local/lib/python2.7/dist-packages/update_checker.py", line 177, in update_check
    result = checker.check(package_name, package_version, **extra_data)
  File "/usr/local/lib/python2.7/dist-packages/update_checker.py", line 68, in wrapped
    retval = function(obj, package_name, package_version, **extra_data)
  File "/usr/local/lib/python2.7/dist-packages/update_checker.py", line 144, in check
    release_date=data['data']['upload_time'])
  File "/usr/local/lib/python2.7/dist-packages/update_checker.py", line 89, in __init__
    '%Y-%m-%dT%H:%M:%S')
AttributeError: _strptime
```

**Comment by bboe** [comment]
Resolved by 48e1b8f260e7cfbdc90e6b4dc756813e4149495d.
