### ISSUE TITLE
0.18.0 has syntax errors

### ISSUE THREAD

**Issue by rawOrlando** [bboe/update_checker#17]
```
                   ERROR: Command errored out with exit status 1:
                   command: /opt/strongarm_venv/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Qu_7kU/update-checker/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Qu_7kU/update-checker/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ceql0H
                       cwd: /tmp/pip-install-Qu_7kU/update-checker/
                  Complete output (6 lines):
                  Traceback (most recent call last):
                    File "<string>", line 1, in <module>
                    File "/tmp/pip-install-Qu_7kU/update-checker/setup.py", line 9
                      with open(f"{MODULE_NAME}.py") as fp:
                                                  ^
                  SyntaxError: invalid syntax
```

**Comment by rawOrlando** [comment]
nvm, y'all dropped support for python 2

**Comment by bboe** [comment]
Yes, as of this version only python 3.6+ is supported.
